// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvK2SEaBTV2tUo6hbSv4xi5mh4i-9Ea4E',
    appId: '1:230006065254:web:4c95ce03276ac70e60c5a7',
    messagingSenderId: '230006065254',
    projectId: 'jimpitan-26fda',
    authDomain: 'jimpitan-26fda.firebaseapp.com',
    storageBucket: 'jimpitan-26fda.firebasestorage.app',
    measurementId: 'G-18GE22356Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApQtXmbwgXy_5XDcgwFYONeHFwsmqdLJE',
    appId: '1:230006065254:android:685d7561cacac3c160c5a7',
    messagingSenderId: '230006065254',
    projectId: 'jimpitan-26fda',
    storageBucket: 'jimpitan-26fda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfRw6UW6H5cJZuhYyuxxWyekgQQorb3Xg',
    appId: '1:230006065254:ios:37f9f6228e72413860c5a7',
    messagingSenderId: '230006065254',
    projectId: 'jimpitan-26fda',
    storageBucket: 'jimpitan-26fda.firebasestorage.app',
    iosBundleId: 'com.example.jimpitan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfRw6UW6H5cJZuhYyuxxWyekgQQorb3Xg',
    appId: '1:230006065254:ios:37f9f6228e72413860c5a7',
    messagingSenderId: '230006065254',
    projectId: 'jimpitan-26fda',
    storageBucket: 'jimpitan-26fda.firebasestorage.app',
    iosBundleId: 'com.example.jimpitan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvK2SEaBTV2tUo6hbSv4xi5mh4i-9Ea4E',
    appId: '1:230006065254:web:075236a2163d0ee860c5a7',
    messagingSenderId: '230006065254',
    projectId: 'jimpitan-26fda',
    authDomain: 'jimpitan-26fda.firebaseapp.com',
    storageBucket: 'jimpitan-26fda.firebasestorage.app',
    measurementId: 'G-7N4VVD83V7',
  );
}
